# Docker Compose untuk Serverless (SQLite, single container)
version: '3.8'

services:
  # WhatsApp Bot untuk Serverless
  whatsapp-bot:
    build: .
    container_name: whatsapp-financial-bot-serverless
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_TYPE=sqlite3
      - DB_PATH=/app/data/financial.db
      - ENABLE_AI_FEATURES=true
      - LOG_LEVEL=info
      # Environment variables untuk serverless
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - BOT_ADMIN_PHONE=${BOT_ADMIN_PHONE}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - BOT_NAME=${BOT_NAME:-Financial Bot}
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - app_backups:/app/backups
    ports:
      - "3000:3000"

volumes:
  app_data:
  app_logs:
  app_backups: