# Docker Compose untuk Development (SQLite)
version: '3.8'

services:
  # WhatsApp Bot Development
  whatsapp-bot-dev:
    build: .
    container_name: whatsapp-financial-bot-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_TYPE=sqlite3
      - DB_PATH=/app/data/financial_dev.db
      - ENABLE_AI_FEATURES=true
      - LOG_LEVEL=debug
      # Development environment variables
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-your_dev_api_key}
      - BOT_ADMIN_PHONE=${BOT_ADMIN_PHONE:-+62xxxxxxxxxx}
      - ALLOWED_USERS=${ALLOWED_USERS:-}
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./data/sessions:/app/data/sessions
      - ./logs:/app/logs
      - ./backups:/app/backups
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - bot-dev-network

networks:
  bot-dev-network:
    driver: bridge