version: '3.8'

services:
  # WhatsApp Bot Development Service
  whatsapp-bot-dev:
    build:
      context: .
      target: builder
    container_name: whatsapp-financial-bot-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_TYPE=sqlite3
      - DB_PATH=/app/data/financial_dev.db
      - ENABLE_AI_FEATURES=true
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    ports:
      - "3000:3000"
    command: sh -c "npm run setup && npm run dev"
    networks:
      - bot-dev-network

  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: postgres-financial-bot-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=financial_bot_dev
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bot-dev-network

  # pgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-financial-bot
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@financialbot.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres-dev
    networks:
      - bot-dev-network

volumes:
  postgres_dev_data:

networks:
  bot-dev-network:
    driver: bridge