version: '3.8'

services:
  # WhatsApp Bot Service
  whatsapp-bot:
    build: .
    container_name: whatsapp-financial-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=financial_bot
      - DB_USER=botuser
      - DB_PASSWORD=botpassword
      - ENABLE_AI_FEATURES=true
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot-network
    command: sh -c "npm run setup && npm start"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres-financial-bot
    restart: unless-stopped
    environment:
      - POSTGRES_DB=financial_bot
      - POSTGRES_USER=botuser
      - POSTGRES_PASSWORD=botpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - bot-network

  # Redis (optional, for future caching)
  redis:
    image: redis:7-alpine
    container_name: redis-financial-bot
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-network

volumes:
  postgres_data:
  redis_data:

networks:
  bot-network:
    driver: bridge