# Nixpacks configuration for WhatsApp Financial Bot

[phases.setup]
nixPkgs = [
  "nodejs_18",
  "npm",
  "sqlite",
  "postgresql",
  "chromium"
]

[phases.install]
cmds = [
  "npm ci --production",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "npm run setup",
  "npm run setup-db"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*/bin/chromium"

[staticAssets]
"data" = "data"
"logs" = "logs"
"backups" = "backups"

[postgres]
enabled = true
version = "15"

[healthcheck]
path = "/health"