[variables]
NODE_VERSION = "20"
NPM_VERSION = "9"
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "info"
DATABASE_TYPE = "sqlite3"
DB_PATH = "./data/financial.db"
ENABLE_AI_FEATURES = "true"
ENABLE_OCR = "false"
ENABLE_REMINDERS = "true"
TZ = "Asia/Jakarta"

[phases.setup]
nixPkgs = [
    "nodejs_20",
    "npm",
    "git",
    "sqlite",
    "postgresql",
    "python3",
    "gnumake",
    "gcc",
    "pkg-config",
    "libtool",
    "autoconf",
    "automake"
]

[phases.install]
cmds = [
    "npm ci --production"
]

[phases.build]
cmds = [
    "mkdir -p data data/sessions logs backups",
    "chmod 755 data data/sessions logs backups",
    "chmod +x scripts/create-env.js",
    "node scripts/create-env.js"
]

[start]
cmd = "node src/index.js"

[staticAssets]
"src/public" = "./"