[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
NODE_VERSION = "20"
NPM_VERSION = "9"
DATABASE_TYPE = "postgresql"
PORT = "3000"
LOG_LEVEL = "info"
ENABLE_AI_FEATURES = "true"
ENABLE_OCR = "false" 
ENABLE_REMINDERS = "true"
TZ = "Asia/Jakarta"
DEFAULT_LANGUAGE = "id"
DEFAULT_CURRENCY = "IDR"
CURRENCY_SYMBOL = "Rp"
ASK_CATEGORY_IF_UNKNOWN = "true"
LOG_FILE = "./logs/app.log"
BACKUP_PATH = "./backups"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "development"
DATABASE_TYPE = "sqlite3"
DB_PATH = "./data/financial_staging.db"
LOG_LEVEL = "debug"